import { SubjectMaterial, NoteItem, TestItem, TestResultRecord } from './types';

export const STUDY_MATERIALS: SubjectMaterial[] = [
  // Class 12th Materials
  {
    id: 'class-12-physics-mat',
    name: '12th Physics',
    icon: '⚛️',
    grade: 'Class 12th',
    description: 'Electrostatics, Optics, Magnetism & Modern Physics',
    chaptersCount: 14,
    chapters: [
      { title: 'Chapter 1: Electric Charges and Fields', description: 'Coulomb’s law, electric field lines, electric dipole, and Gauss’s law with applications.', pdfSize: '4.8 MB', readTime: '25 min read' },
      { title: 'Chapter 2: Electrostatic Potential & Capacitance', description: 'Equipotential surfaces, potential energy of dipole, parallel plate capacitors & dielectrics.', pdfSize: '5.2 MB', readTime: '28 min read' },
      { title: 'Chapter 3: Current Electricity', description: 'Drift velocity, Ohm’s law, Kirchhoff’s rules, Wheatstone bridge, and potentiometer principle.', pdfSize: '4.6 MB', readTime: '24 min read' },
      { title: 'Chapter 4: Moving Charges and Magnetism', description: 'Biot-Savart law, Ampere’s circuital law, solenoid, toroid, and cyclotron principle.', pdfSize: '5.0 MB', readTime: '26 min read' },
      { title: 'Chapter 5: Electromagnetic Induction & AC', description: 'Faraday’s laws, Lenz’s law, eddy currents, LCR series circuit, and electrical resonance.', pdfSize: '5.5 MB', readTime: '30 min read' },
      { title: 'Chapter 6: Ray Optics & Wave Optics', description: 'Refraction at spherical surfaces, lens maker formula, prism dispersion, and YDSE interference.', pdfSize: '6.1 MB', readTime: '35 min read' },
    ],
  },
  {
    id: 'class-12-chemistry-mat',
    name: '12th Chemistry',
    icon: '🧪',
    grade: 'Class 12th',
    description: 'Solutions, Kinetics, Coordination & Organic Chemistry',
    chaptersCount: 16,
    chapters: [
      { title: 'Chapter 1: Solutions', description: 'Henry’s law, Raoult’s law, colligative properties, van ’t Hoff factor, and abnormal molar mass.', pdfSize: '4.4 MB', readTime: '22 min read' },
      { title: 'Chapter 2: Electrochemistry', description: 'Galvanic cells, Nernst equation, Kohlrausch’s law of independent ionic migration, fuel cells.', pdfSize: '4.9 MB', readTime: '26 min read' },
      { title: 'Chapter 3: Chemical Kinetics', description: 'Rate law, order and molecularity, integrated rate equations, pseudo 1st order, Arrhenius theory.', pdfSize: '4.1 MB', readTime: '20 min read' },
      { title: 'Chapter 4: d and f Block Elements', description: 'Transition metal characteristics, variable oxidation states, lanthanoid contraction, KMnO₄ & K₂Cr₂O₇.', pdfSize: '4.7 MB', readTime: '25 min read' },
      { title: 'Chapter 5: Coordination Compounds', description: 'Werner’s theory, IUPAC nomenclature, isomerism, Valence Bond Theory (VBT), and Crystal Field Theory (CFT).', pdfSize: '5.3 MB', readTime: '28 min read' },
      { title: 'Chapter 6: Aldehydes, Ketones & Carboxylic Acids', description: 'Nucleophilic addition, Aldol condensation, Cannizzaro reaction, Clemmensen and Wolff-Kishner reduction.', pdfSize: '5.8 MB', readTime: '32 min read' },
    ],
  },
  {
    id: 'class-12-maths-mat',
    name: '12th Mathematics',
    icon: '📐',
    grade: 'Class 12th',
    description: 'Calculus, Vectors, 3D Geometry, Matrices & Probability',
    chaptersCount: 13,
    chapters: [
      { title: 'Chapter 1: Matrices & Determinants', description: 'Matrix operations, adjoint and inverse, solving linear system of equations using matrix method.', pdfSize: '4.3 MB', readTime: '22 min read' },
      { title: 'Chapter 2: Continuity and Differentiability', description: 'Chain rule, parametric differentiation, logarithmic differentiation, and Mean Value Theorems.', pdfSize: '5.1 MB', readTime: '27 min read' },
      { title: 'Chapter 3: Integrals (Definite & Indefinite)', description: 'Integration by substitution, partial fractions, integration by parts (ILATE), King’s properties.', pdfSize: '6.2 MB', readTime: '35 min read' },
      { title: 'Chapter 4: Differential Equations', description: 'Order and degree, variable separable method, homogeneous equations, linear differential equations with IF.', pdfSize: '4.6 MB', readTime: '24 min read' },
      { title: 'Chapter 5: Vector Algebra & 3D Geometry', description: 'Scalar and vector products, direction cosines, vector equation of a line, shortest distance between skew lines.', pdfSize: '5.7 MB', readTime: '30 min read' },
      { title: 'Chapter 6: Probability & Bayes’ Theorem', description: 'Conditional probability, multiplication theorem, independent events, Bayes’ rule, and binomial distribution.', pdfSize: '4.5 MB', readTime: '24 min read' },
    ],
  },
  {
    id: 'class-12-english-mat',
    name: '12th English Core',
    icon: '📖',
    grade: 'Class 12th',
    description: 'Flamingo, Vistas, Reading & Advanced Writing Skills',
    chaptersCount: 14,
    chapters: [
      { title: 'Section A: Advanced Reading Skills', description: 'Discursive and case-based factual passages, vocabulary inferences, central theme identification.', pdfSize: '2.8 MB', readTime: '18 min read' },
      { title: 'Section B: Creative Writing Skills', description: 'Notice writing, formal invitations & replies, letters to editor/job applications, article & report writing.', pdfSize: '3.4 MB', readTime: '20 min read' },
      { title: 'Flamingo: Prose In-depth Summaries', description: 'The Last Lesson, Lost Spring, Deep Water, The Rattrap, Indigo, Poets and Pancakes.', pdfSize: '4.2 MB', readTime: '26 min read' },
      { title: 'Flamingo: Poetry Analysis', description: 'My Mother at Sixty-Six, Keeping Quiet, A Thing of Beauty, A Roadside Stand, Aunt Jennifer’s Tigers.', pdfSize: '3.1 MB', readTime: '19 min read' },
      { title: 'Vistas: Supplementary Reader', description: 'The Third Level, The Tiger King, Journey to the End of the Earth, The Enemy, On the Face of It.', pdfSize: '3.9 MB', readTime: '24 min read' },
    ],
  },

  // Class 10th Materials
  {
    id: 'math',
    name: 'Mathematics (Class 10th)',
    icon: '📘',
    grade: 'Class 10th',
    description: 'Chapter-wise study material',
    chaptersCount: 15,
    chapters: [
      { title: 'Chapter 1: Real Numbers', description: 'Fundamental Theorem of Arithmetic, Euclid division lemma, irrational proofs.', pdfSize: '2.4 MB', readTime: '15 min read' },
      { title: 'Chapter 2: Polynomials', description: 'Zeroes of a polynomial, quadratic factorizations, relationship between zeroes & coefficients.', pdfSize: '3.1 MB', readTime: '20 min read' },
      { title: 'Chapter 3: Linear Equations in Two Variables', description: 'Graphical method, elimination, substitution, and real-world word problems.', pdfSize: '4.2 MB', readTime: '25 min read' },
      { title: 'Chapter 4: Quadratic Equations', description: 'Discriminant nature of roots, completing the square, quadratic formula.', pdfSize: '3.8 MB', readTime: '22 min read' },
      { title: 'Chapter 5: Arithmetic Progressions', description: 'Nth term formula, sum of first n terms, and sequence word problems.', pdfSize: '2.9 MB', readTime: '18 min read' },
      { title: 'Chapter 6: Triangles & Coordinate Geometry', description: 'Similarity criteria, Basic Proportionality Theorem, distance and section formula.', pdfSize: '5.1 MB', readTime: '30 min read' },
    ],
  },
  {
    id: 'science',
    name: 'Science (Class 10th)',
    icon: '🔬',
    grade: 'Class 10th',
    description: 'Physics, Chemistry & Biology',
    chaptersCount: 16,
    chapters: [
      { title: 'Physics: Light - Reflection and Refraction', description: 'Mirror formula, magnification, Snell law, lens formula and ray diagrams.', pdfSize: '4.5 MB', readTime: '25 min read' },
      { title: 'Physics: Electricity & Magnetism', description: 'Ohm law, series and parallel circuits, Joule law of heating, electromagnetic induction.', pdfSize: '4.8 MB', readTime: '28 min read' },
      { title: 'Chemistry: Chemical Reactions & Equations', description: 'Balancing chemical equations, redox, displacement, endothermic & exothermic reactions.', pdfSize: '3.3 MB', readTime: '20 min read' },
      { title: 'Chemistry: Acids, Bases and Salts', description: 'pH scale, neutralization, bleaching powder, baking soda, and plaster of Paris.', pdfSize: '3.6 MB', readTime: '22 min read' },
      { title: 'Biology: Life Processes', description: 'Nutrition in plants and humans, respiration, circulatory system, and excretion in kidneys.', pdfSize: '5.5 MB', readTime: '32 min read' },
      { title: 'Biology: Control and Coordination', description: 'Nervous system, neuron structure, reflex arc, human brain and phytohormones.', pdfSize: '3.9 MB', readTime: '24 min read' },
    ],
  },
  {
    id: 'english',
    name: 'English (Class 10th)',
    icon: '📖',
    grade: 'Class 10th',
    description: 'Grammar & literature material',
    chaptersCount: 12,
    chapters: [
      { title: 'Grammar: Tenses & Subject-Verb Concord', description: 'Rules of agreement, common pitfalls, present perfect vs past simple usage.', pdfSize: '1.8 MB', readTime: '15 min read' },
      { title: 'Grammar: Active and Passive Voice', description: 'Conversion rules for all 12 tenses, imperative and interrogative transformation.', pdfSize: '2.0 MB', readTime: '16 min read' },
      { title: 'Grammar: Reported Speech (Direct & Indirect)', description: 'Change of pronouns, tense changes, reporting modal verbs and reporting questions.', pdfSize: '2.2 MB', readTime: '18 min read' },
      { title: 'Writing Skills: Analytical Paragraph & Formal Letters', description: 'Letter to editor, complaint letters, data graph summaries with ideal formats.', pdfSize: '2.5 MB', readTime: '20 min read' },
      { title: 'Literature: First Flight Key Summaries', description: 'Detailed chapter summaries, character sketches, and previous years exam questions.', pdfSize: '4.1 MB', readTime: '30 min read' },
    ],
  },
  {
    id: 'sst',
    name: 'Social Science (Class 10th)',
    icon: '🌍',
    grade: 'Class 10th',
    description: 'History, Geography & Civics',
    chaptersCount: 18,
    chapters: [
      { title: 'History: The Rise of Nationalism in Europe', description: 'French Revolution, Romantic imagination, unification of Italy and Germany.', pdfSize: '4.2 MB', readTime: '28 min read' },
      { title: 'History: Nationalism in India', description: 'Non-Cooperation movement, Salt Satyagraha, Civil Disobedience, Simon Commission.', pdfSize: '4.0 MB', readTime: '26 min read' },
      { title: 'Geography: Resources and Development', description: 'Classification of resources, soil erosion, conservation and land utilization in India.', pdfSize: '3.5 MB', readTime: '22 min read' },
      { title: 'Geography: Water & Mineral Resources', description: 'Dams, rainwater harvesting, distribution of iron ore, bauxite and coal reserves.', pdfSize: '3.7 MB', readTime: '24 min read' },
      { title: 'Civics: Power Sharing & Federalism', description: 'Belgium model vs Sri Lanka, decentralization in India, 73rd and 74th amendments.', pdfSize: '3.0 MB', readTime: '20 min read' },
      { title: 'Economics: Sectors of the Indian Economy', description: 'Primary, secondary, tertiary sectors, disguised unemployment, MGNREGA 2005.', pdfSize: '2.8 MB', readTime: '19 min read' },
    ],
  },
];

export const REVISION_NOTES: NoteItem[] = [
  // Class 12th Physics
  {
    id: 'class-12-physics',
    subject: '12th Class Physics',
    grade: 'Class 12th',
    icon: '⚛️',
    description: 'Electrostatics, Optics, Magnetism, EMI, AC & Modern Physics',
    keyPoints: [
      'Gauss’s Law: Total electric flux Φ = ∮ E·dA = q_enc / ε₀. Field of infinite thin charged plane sheet is E = σ / (2ε₀).',
      'Electric Potential & Dipole: Potential V = kq / r; Torque on dipole τ = p × E; Potential energy U = -p · E.',
      'Capacitance: Parallel plate capacitor C = (K·ε₀·A) / d; with dielectric slab of thickness t: C = ε₀A / [d - t(1 - 1/K)]. Energy U = ½CV².',
      'Kirchhoff’s Rules: Junction rule ΣI = 0 (conservation of charge); Loop rule ΣΔV = 0 (conservation of energy).',
      'Ampere’s Circuital Law: ∮ B·dl = μ₀I_enc. Long solenoid field B = μ₀nI; Toroid field B = (μ₀NI) / (2πr).',
      'Faraday’s Law & Lenz’s Law: Induced emf e = -dΦ/dt = -N d(B·A)/dt. Lenz’s law enforces energy conservation.',
      'LCR Resonance: At resonance, inductive reactance equals capacitive reactance (ωL = 1/ωC); Z_min = R; Current is maximum.',
      'Optics: Lens Maker’s formula 1/f = (μ - 1)(1/R₁ - 1/R₂). In YDSE, fringe width β = λD / d.',
      'Photoelectric Effect: Einstein equation K_max = hν - Φ₀ = eV₀. Stopping potential depends linearly on incident frequency.',
      'de Broglie hypothesis: Matter waves λ = h / p = 1.227 / √V nm for electrons accelerated through V volts.',
    ],
    formulas: [
      { name: 'Coulomb’s Force Law', formula: 'F = (1 / 4πε₀) · (|q₁q₂| / r²)' },
      { name: 'Capacitor Energy & Density', formula: 'U = (1/2) C V² = Q² / (2C);  u = (1/2) ε₀ E²' },
      { name: 'Drift Velocity & Current', formula: 'I = n · e · A · v_d,  where v_d = (e · E · τ) / m' },
      { name: 'Biot-Savart Law', formula: 'dB = (μ₀ / 4π) · (I dl sinθ / r²)' },
      { name: 'Motional EMF & Inductance', formula: 'ε = B · l · v;  Self-induced emf e = -L(dI/dt)' },
      { name: 'LCR Series Impedance', formula: 'Z = √[R² + (ωL - 1/(ωC))²];  f_res = 1 / (2π √(LC))' },
      { name: 'Lens Maker’s Equation', formula: '1/f = (n₂/n₁ - 1) · (1/R₁ - 1/R₂)' },
      { name: 'YDSE Fringe Width', formula: 'β = (λ · D) / d;  Path diff for maxima Δx = nλ' },
      { name: 'Einstein Photoelectric Equation', formula: 'hν = Φ₀ + K_max = hν₀ + e · V₀' },
      { name: 'Bohr Energy Levels (Hydrogen)', formula: 'E_n = -13.6 / n²  eV;  r_n = 0.529 · n²  Å' },
    ],
    chapters: [
      {
        title: 'Electrostatics & Current Electricity',
        keyPoints: [
          'Electric field due to point charge: E = kq / r² directed radially outward for positive charge.',
          'Electric dipole: Electric field at axial point E_axial = (2kp) / r³; equatorial point E_equatorial = (kp) / r³.',
          'Capacitance of parallel plate capacitor with dielectric: C = K·ε₀·A / d. When plates are disconnected from battery, charge Q remains constant while V drops.',
          'Ohm’s law in microscopic form: j = σ·E (Current density = conductivity × electric field).',
          'Wheatstone Bridge balance condition: P/Q = R/S with zero galvanometer deflection.',
        ],
        formulas: [
          { name: 'Gauss’s Law Flux', formula: 'Φ_E = ∮ E · dA = q_enclosed / ε₀' },
          { name: 'Parallel Plate Capacitance', formula: 'C = (K · ε₀ · A) / d' },
          { name: 'Current & Drift Velocity', formula: 'I = n · e · A · v_d  [v_d = eEτ/m]' },
          { name: 'Temperature Coefficient of R', formula: 'R_T = R₀ [1 + α(T - T₀)]' },
          { name: 'Wheatstone Condition', formula: 'P / Q = R / S' },
        ],
      },
      {
        title: 'Magnetism, EMI & Alternating Current',
        keyPoints: [
          'Magnetic Lorentz Force: F = q(E + v × B). No work is done by magnetic field on a charged particle because F is perpendicular to v.',
          'Ampere’s Circuital Law: Line integral ∮ B·dl = μ₀ I_enclosed.',
          'Force between two parallel long currents: F/L = (μ₀ I₁ I₂) / (2π d). Attract if currents in same direction, repel if opposite.',
          'Faraday’s Law: Induced electromotive force e = -dΦ_B / dt. Minus sign represents Lenz’s law (reaction opposing cause).',
          'AC Series LCR: Phase angle tan φ = (X_L - X_C) / R. At resonance, power factor cos φ = 1.',
        ],
        formulas: [
          { name: 'Lorentz Force on Charge', formula: 'F = q (E + v × B)' },
          { name: 'Force between Parallel Wires', formula: 'F / L = (μ₀ · I₁ · I₂) / (2π · d)' },
          { name: 'Faraday-Lenz EMF', formula: 'e = -N · (dΦ / dt)' },
          { name: 'LCR Impedance', formula: 'Z = √[R² + (ωL - 1/(ωC))²]' },
          { name: 'Resonant Frequency', formula: 'f_0 = 1 / [2π √(LC)]' },
        ],
      },
      {
        title: 'Optics (Ray & Wave)',
        keyPoints: [
          'Total Internal Reflection: Occurs when light travels from denser to rarer medium and angle of incidence i > i_c where sin(i_c) = 1/μ.',
          'Lens Maker’s Formula: Relates focal length to radii of curvature R₁ and R₂: 1/f = (μ - 1)(1/R₁ - 1/R₂).',
          'Prism Formula: Refractive index μ = sin[(A + D_m)/2] / sin(A/2), where A is angle of prism and D_m is minimum deviation.',
          'Huygens’ Principle: Every point on a wavefront behaves as a secondary spherical wavelet propagating with speed of wave.',
          'Interference in YDSE: Bright fringes at y = nλD/d; Dark fringes at y = (2n - 1)λD/(2d). Fringe width β = λD/d.',
        ],
        formulas: [
          { name: 'Lens Maker’s Formula', formula: '1/f = (μ - 1) · (1/R₁ - 1/R₂)' },
          { name: 'Prism Refraction Formula', formula: 'μ = sin((A + D_m)/2) / sin(A/2)' },
          { name: 'Compound Microscope Magnification', formula: 'm = -(L / f_o) · (1 + D / f_e)' },
          { name: 'Astronomical Telescope Magnification', formula: 'm = -f_o / f_e,  Tube length L = f_o + f_e' },
          { name: 'YDSE Fringe Width', formula: 'β = (λ · D) / d' },
        ],
      },
      {
        title: 'Modern Physics & Semiconductors',
        keyPoints: [
          'Photoelectric Effect: Instantaneous emission without time lag; maximum kinetic energy depends on frequency, not intensity.',
          'de Broglie Wavelength: λ = h / p = h / √(2mE). For electron: λ = 12.27 / √V Å.',
          'Bohr Postulate: Angular momentum quantized as L = mvr = nh / (2π). Energy of n-th orbit is -13.6/n² eV.',
          'Mass Defect & Binding Energy: Δm = [Zm_p + (A - Z)m_n] - M_nucleus. B.E. per nucleon determines nuclear stability.',
          'Semiconductors: Intrinsic (n_e = n_h = n_i). Extrinsic: n-type (pentavalent, majority electrons), p-type (trivalent, majority holes).',
        ],
        formulas: [
          { name: 'Photoelectric Equation', formula: 'K_max = hν - Φ₀ = e · V₀' },
          { name: 'de Broglie Wavelength', formula: 'λ = h / √(2m · q · V) = 1.227 / √V  nm' },
          { name: 'Rydberg Wave Number', formula: '1/λ = R · [1/n₁² - 1/n₂²]  (R ≈ 1.097 × 10⁷ m⁻¹)' },
          { name: 'Nuclear Binding Energy', formula: 'BE = Δm × 931.5 MeV  (Δm in amu)' },
          { name: 'Mass Action Law', formula: 'n_e · n_h = n_i²' },
        ],
      },
    ],
  },

  // Class 12th Chemistry
  {
    id: 'class-12-chemistry',
    subject: '12th Class Chemistry',
    grade: 'Class 12th',
    icon: '🧪',
    description: 'Solutions, Electrochemistry, Kinetics, d/f Blocks, Coordination & Organic Reactions',
    keyPoints: [
      'Solutions & Colligative Properties: Depend only on number of solute particles. ΔT_b = i·K_b·m, ΔT_f = i·K_f·m, π = i·C·R·T.',
      'Van’t Hoff factor i: i = 1 + (n - 1)α for dissociation; i = 1 + (1/n - 1)β for association.',
      'Nernst Equation: E_cell = E°_cell - (0.0591 / n) log Q at 298 K. At equilibrium, E_cell = 0 and E°_cell = (0.0591 / n) log K_c.',
      'Kohlrausch’s Law: Molar conductivity at infinite dilution is the sum of limiting ionic conductivities of constituent ions.',
      'Chemical Kinetics: For 1st order reaction, k = (2.303 / t) log([A]₀ / [A]), half life t_½ = 0.693 / k (independent of initial concentration).',
      'Lanthanoid Contraction: Due to poor shielding of 4f electrons, atomic/ionic sizes of 4d and 5d series (e.g. Zr & Hf) are nearly identical.',
      'Coordination Compounds: Werner’s theory explains primary (ionizable) and secondary (coordination number) valencies. CFT explains colour via d-d transitions.',
      'Important Named Reactions: Sandmeyer (Ar-X), Reimer-Tiemann (Salicylaldehyde), Kolbe (Salicylic acid), Aldol condensation, Cannizzaro.',
      'Biomolecules: Peptide linkage (-CO-NH-) joins amino acids. Denaturation unfolds secondary and tertiary protein structures leaving primary intact.',
    ],
    formulas: [
      { name: 'Relative Lowering of Vapour Pressure', formula: '(P° - P_s) / P° = i · x_solute' },
      { name: 'Boiling & Freezing Colligative', formula: 'ΔT_b = i · K_b · m;  ΔT_f = i · K_f · m' },
      { name: 'Osmotic Pressure', formula: 'π = i · C · R · T = i · (n/V) · R · T' },
      { name: 'Nernst Equation (at 298 K)', formula: 'E_cell = E°_cell - (0.0591 / n) · log₁₀(Q)' },
      { name: 'Gibbs Free Energy & Cell EMF', formula: 'ΔG° = -n · F · E°_cell = -2.303 · R · T · log₁₀(K_c)' },
      { name: 'First Order Kinetics Constant', formula: 'k = (2.303 / t) · log([A]₀ / [A]);  t_½ = 0.693 / k' },
      { name: 'Arrhenius Activation Energy', formula: 'log(k₂ / k₁) = (E_a / 2.303R) · [(T₂ - T₁) / (T₁T₂)]' },
      { name: 'Spin-Only Magnetic Moment', formula: 'μ = √[n(n + 2)]  BM  (n = unpaired electrons)' },
      { name: 'Reimer-Tiemann Reaction', formula: 'C₆H₅OH + CHCl₃ + 3NaOH -> o-HOC₆H₄CHO (Salicylaldehyde)' },
      { name: 'Aldol Condensation', formula: '2 CH₃CHO (dil. NaOH) -> CH₃CH(OH)CH₂CHO -> CH₃CH=CHCHO + H₂O' },
    ],
    chapters: [
      {
        title: 'Physical Chemistry (Solutions, Electrochemistry & Kinetics)',
        keyPoints: [
          'Henry’s Law: Partial pressure of gas in vapour phase is proportional to mole fraction of gas in solution: p = K_H · x.',
          'Raoult’s Law for volatile solutes: p_total = p_A + p_B = p°_A · x_A + p°_B · x_B.',
          'Electrochemical Cell vs Electrolytic Cell: Galvanic produces electricity (ΔG < 0); Electrolytic consumes electricity (ΔG > 0).',
          'Molar Conductivity: Λ_m = (1000 · κ) / M. Degree of dissociation α = Λ_m / Λ°_m.',
          'Arrhenius Equation: k = A · e^(-E_a / RT). Slope of log k vs 1/T is -E_a / (2.303 R).',
        ],
        formulas: [
          { name: 'Raoult’s Law Lowering', formula: '(P° - P_s) / P° = i · [n_solute / (n_solute + n_solvent)]' },
          { name: 'Van’t Hoff Factor Relation', formula: 'i = 1 + (n - 1)α  (Dissociation); i = 1 + (1/n - 1)β (Association)' },
          { name: 'Nernst EMF at 298K', formula: 'E_cell = E°_cell - (0.0591 / n) log Q' },
          { name: 'Kohlrausch’s Additivity', formula: 'Λ°_m = ν₊ · λ°₊ + ν₋ · λ°₋' },
          { name: '1st Order Rate Constant', formula: 'k = (2.303 / t) · log([A]₀ / [A])' },
        ],
      },
      {
        title: 'Inorganic Chemistry (d & f Blocks, Coordination)',
        keyPoints: [
          'Transition Metals: Exhibit variable oxidation states, catalytic properties, formation of coloured ions, and interstitial complexes.',
          'Magnetic Properties: Diamagnetic (all electrons paired), Paramagnetic (unpaired electrons present), calculated via spin-only formula μ = √[n(n+2)] BM.',
          'Lanthanoid Contraction: The steady decrease in radii of Lanthanoids (La³⁺ to Lu³⁺) due to poor shielding of 4f electrons.',
          'Crystal Field Theory (CFT): In octahedral field, d-orbitals split into t₂g (lower energy by -0.4Δ₀) and eg (higher energy by +0.6Δ₀).',
          'Spectrochemical Series: Ligand field strength: I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < en < CN⁻ < CO. Strong field ligands cause low-spin complexes.',
        ],
        formulas: [
          { name: 'Spin-Only Magnetic Moment', formula: 'μ = √[n(n + 2)]  Bohr Magnetons' },
          { name: 'Octahedral CFSE', formula: 'CFSE = [-0.4 · n(t₂g) + 0.6 · n(eg)] Δ₀ + mP' },
          { name: 'Tetrahedral vs Octahedral', formula: 'Δ_t = (4/9) · Δ₀' },
          { name: 'IUPAC Coordination Rule', formula: '[Co(NH₃)₆]Cl₃ -> Hexaamminecobalt(III) chloride' },
        ],
      },
      {
        title: 'Organic Chemistry (Reactions & Mechanisms)',
        keyPoints: [
          'Haloalkanes & Haloarenes: S_N2 mechanism proceeds via single step with inversion of configuration; S_N1 proceeds via carbocation with racemisation.',
          'Lucas Test: Conc. HCl + anhydrous ZnCl₂. 3° alcohol gives immediate turbidity, 2° gives within 5 mins, 1° does not give turbidity at room temperature.',
          'Kolbe’s Synthesis: Sodium phenoxide reacts with CO₂ followed by acidification to produce Salicylic acid (precursor to aspirin).',
          'Cannizzaro Reaction: Aldehydes lacking α-hydrogen (HCHO, Benzaldehyde) disproportionate in 50% conc. NaOH to alcohol + salt of acid.',
          'Gabriel Phthalimide Synthesis: Selectively produces 1° aliphatic amines without contamination of 2° or 3° amines.',
        ],
        formulas: [
          { name: 'Sandmeyer Diazotisation', formula: 'Ar-NH₂ + NaNO₂ + 2HCl -> Ar-N₂⁺Cl⁻ + CuCl -> Ar-Cl + N₂' },
          { name: 'Reimer-Tiemann Salicylaldehyde', formula: 'Phenol + CHCl₃ + 3 NaOH -> Salicylaldehyde' },
          { name: 'Kolbe Salicylic Acid', formula: 'Sodium phenoxide + CO₂ (4-7 atm, 400K) + H⁺ -> Salicylic Acid' },
          { name: 'Clemmensen Reduction', formula: '>C=O + Zn-Hg / conc. HCl -> >CH₂ + H₂O' },
          { name: 'Wolff-Kishner Reduction', formula: '>C=O + NH₂-NH₂ / KOH (ethylene glycol, Δ) -> >CH₂' },
          { name: 'Hinsberg Amine Test', formula: '1° Amine + C₆H₅SO₂Cl -> Soluble in alkali' },
        ],
      },
    ],
  },

  // Class 12th Mathematics
  {
    id: 'class-12-maths',
    subject: '12th Class Mathematics',
    grade: 'Class 12th',
    icon: '📐',
    description: 'Calculus, Integrals, Differential Equations, Vectors, 3D Geometry, Matrices & Probability',
    keyPoints: [
      'Matrices & Determinants: A · adj(A) = |A| · I. Matrix inverse A⁻¹ = (1 / |A|) · adj(A) exists only if |A| ≠ 0. Determinant of adj(A): |adj(A)| = |A|^(n-1).',
      'Inverse Trigonometric Functions: Principal branches: sin⁻¹x ∈ [-π/2, π/2], cos⁻¹x ∈ [0, π], tan⁻¹x ∈ (-π/2, π/2). sin⁻¹x + cos⁻¹x = π/2.',
      'Calculus - Continuity & Differentiability: A function is continuous if LHL = RHL = f(c). Differentiability implies continuity, but continuity does not imply differentiability.',
      'Integration by Parts: ∫ u v dx = u ∫ v dx - ∫ [u\' ∫ v dx] dx following the ILATE priority rule (Inverse, Logarithmic, Algebraic, Trigonometric, Exponential).',
      'Special Integral: ∫ e^x [f(x) + f\'(x)] dx = e^x · f(x) + C.',
      'Definite Integral King’s Property: ∫[0 to a] f(x) dx = ∫[0 to a] f(a - x) dx. Used extensively to solve symmetric trigonometric integrals.',
      'Differential Equations: Linear differential equation dy/dx + Py = Q has integrating factor IF = e^(∫P dx), solution: y · IF = ∫ (Q · IF) dx + C.',
      'Vectors & 3D Geometry: Vector dot product a·b = |a||b|cosθ, projection of a on b is (a·b)/|b|. Cross product a × b is perpendicular to both a and b.',
      'Shortest Distance between Skew Lines: d = |(a₂ - a₁) · (b₁ × b₂)| / |b₁ × b₂|.',
      'Probability: Bayes’ Theorem: P(E_i | A) = [P(E_i) P(A|E_i)] / [Σ P(E_j) P(A|E_j)]. Binomial: P(X = r) = ⁿC_r p^r q^(n - r).',
    ],
    formulas: [
      { name: 'Matrix Inverse & Determinant', formula: 'A⁻¹ = (1 / |A|) · adj(A);  |adj(A)| = |A|^(n - 1)' },
      { name: 'Inverse Trig Addition', formula: 'tan⁻¹(x) + tan⁻¹(y) = tan⁻¹[(x + y) / (1 - xy)]  (xy < 1)' },
      { name: 'Integration by Parts (ILATE)', formula: '∫ u·v dx = u ∫ v dx - ∫ [u\' · (∫ v dx)] dx' },
      { name: 'Special Integral Formula', formula: '∫ e^x [f(x) + f\'(x)] dx = e^x · f(x) + C' },
      { name: 'Standard Integral: 1 / (x² - a²)', formula: '∫ dx / (x² - a²) = (1 / 2a) · ln|(x - a) / (x + a)| + C' },
      { name: 'Standard Integral: √(a² - x²)', formula: '∫ √(a² - x²) dx = (x/2)√(a² - x²) + (a²/2) sin⁻¹(x/a) + C' },
      { name: 'Linear D.E. Integrating Factor', formula: 'IF = e^(∫ P dx);  y · IF = ∫ (Q · IF) dx + C' },
      { name: 'Shortest Distance (Skew Lines)', formula: 'd = |(a₂ - a₁) · (b₁ × b₂)| / |b₁ × b₂|' },
      { name: 'Distance between Parallel Lines', formula: 'd = |b × (a₂ - a₁)| / |b|' },
      { name: 'Bayes’ Theorem Formula', formula: 'P(E_i | A) = [P(E_i) · P(A|E_i)] / [∑ P(E_j) · P(A|E_j)]' },
    ],
    chapters: [
      {
        title: 'Matrices, Determinants & Relations',
        keyPoints: [
          'Relations: A relation R on set A is an Equivalence Relation if it is Reflexive, Symmetric, and Transitive.',
          'Functions: One-one (Injective), Onto (Surjective), and Bijective (both one-one and onto). Inverse exists if and only if bijective.',
          'Matrix Transpose & Symmetry: Symmetric if A^T = A; Skew-symmetric if A^T = -A (all diagonal elements are 0). Any square matrix can be uniquely written as sum of symmetric and skew-symmetric.',
          'Determinants Properties: |A^T| = |A|, |AB| = |A||B|, |k·A| = k^n |A| for n×n matrix.',
          'Matrix Method for Equations: AX = B -> X = A⁻¹B where A⁻¹ = adj(A) / |A|.',
        ],
        formulas: [
          { name: 'Matrix Inverse', formula: 'A⁻¹ = (1 / |A|) · adj(A)' },
          { name: 'Adjoint Properties', formula: 'A · adj(A) = |A| · I;  |adj(A)| = |A|^(n - 1)' },
          { name: 'Linear System Solution', formula: 'X = A⁻¹ · B = (adj(A) · B) / |A|' },
          { name: 'Inverse Trig Complementary', formula: 'sin⁻¹x + cos⁻¹x = π/2;  tan⁻¹x + cot⁻¹x = π/2' },
          { name: 'Inverse Trig 2tan⁻¹x', formula: '2 tan⁻¹x = sin⁻¹(2x / (1 + x²)) = cos⁻¹((1 - x²) / (1 + x²))' },
        ],
      },
      {
        title: 'Calculus (Differential & Integral)',
        keyPoints: [
          'Derivative of Parametric Functions: dy/dx = (dy/dt) / (dx/dt); d²y/dx² = [d/dt(dy/dx)] · (dt/dx).',
          'Maxima & Minima: At stationary point f\'(c) = 0. If f\'\'(c) < 0, local maximum; if f\'\'(c) > 0, local minimum.',
          'Standard Indefinite Integrals: ∫ dx / √(a² - x²) = sin⁻¹(x/a) + C; ∫ dx / (x² + a²) = (1/a) tan⁻¹(x/a) + C.',
          'Definite Integral King’s Rule: ∫[0 to a] f(x) dx = ∫[0 to a] f(a - x) dx.',
          'Area of Bounded Region: Area = ∫[a to b] [y_upper - y_lower] dx.',
        ],
        formulas: [
          { name: 'Integration by Parts', formula: '∫ u·v dx = u ∫ v dx - ∫ [u\' · (∫ v dx)] dx  (ILATE)' },
          { name: 'Exponential Form Integral', formula: '∫ e^x [f(x) + f\'(x)] dx = e^x · f(x) + C' },
          { name: 'Integral 1 / (a² - x²)', formula: '∫ dx / (a² - x²) = (1 / 2a) · ln|(a + x) / (a - x)| + C' },
          { name: 'Integral √(x² + a²)', formula: '∫ √(x² + a²) dx = (x/2)√(x² + a²) + (a²/2) ln|x + √(x² + a²)| + C' },
          { name: 'Definite Integral Symmetry', formula: '∫[-a to a] f(x) dx = 2 ∫[0 to a] f(x) dx  (if f(-x) = f(x))' },
        ],
      },
      {
        title: 'Vectors, 3D Geometry & Probability',
        keyPoints: [
          'Vector Product Properties: a × b = - (b × a). If a × b = 0, then vectors a and b are collinear (parallel).',
          'Scalar Triple Product: [a b c] = a · (b × c) represents volume of parallelepiped. If [a b c] = 0, vectors are coplanar.',
          'Line in 3D: Vector eq: r = a + λ b; Cartesian eq: (x - x₁)/a = (y - y₁)/b = (z - z₁)/c where <a, b, c> are direction ratios.',
          'Shortest Distance between Skew Lines: d = |(a₂ - a₁) · (b₁ × b₂)| / |b₁ × b₂|. If d = 0, lines are intersecting.',
          'Bayes’ Theorem: Used to compute reverse conditional probability of causes given that event A has occurred.',
        ],
        formulas: [
          { name: 'Vector Dot Product & Projection', formula: 'a · b = |a||b| cosθ;  Proj_b(a) = (a · b) / |b|' },
          { name: 'Area of Triangle (Vectors)', formula: 'Area = (1/2) · |a × b|' },
          { name: 'Shortest Distance Formula', formula: 'd = |(a₂ - a₁) · (b₁ × b₂)| / |b₁ × b₂|' },
          { name: 'Distance between Parallel Lines', formula: 'd = |b × (a₂ - a₁)| / |b|' },
          { name: 'Conditional Probability', formula: 'P(A | B) = P(A ∩ B) / P(B)  [P(B) ≠ 0]' },
          { name: 'Bayes’ Theorem', formula: 'P(E_i | A) = [P(E_i) · P(A|E_i)] / [∑ P(E_j) · P(A|E_j)]' },
          { name: 'Binomial Probability', formula: 'P(X = r) = ⁿC_r · p^r · (1 - p)^(n - r)' },
        ],
      },
    ],
  },

  // Class 10th Notes
  {
    id: 'math',
    subject: 'Mathematics (Class 10th)',
    grade: 'Class 10th',
    icon: '📐',
    description: 'Important formulas and concepts',
    keyPoints: [
      'HCF(a, b) × LCM(a, b) = a × b for any two positive integers.',
      'For ax² + bx + c = 0, Sum of zeroes (α + β) = -b/a, Product (αβ) = c/a.',
      'Discriminant D = b² - 4ac: Real & distinct if D > 0, Real & equal if D = 0, No real roots if D < 0.',
      'Nth term of AP: aₙ = a + (n - 1)d. Sum of AP: Sₙ = n/2 [2a + (n - 1)d].',
      'Distance formula: d = √[(x₂ - x₁)² + (y₂ - y₁)²].',
    ],
    formulas: [
      { name: 'Quadratic Formula', formula: 'x = (-b ± √(b² - 4ac)) / (2a)' },
      { name: 'Section Formula', formula: 'P(x, y) = ((m₁x₂ + m₂x₁) / (m₁+m₂), (m₁y₂ + m₂y₁) / (m₁+m₂))' },
      { name: 'Trigonometric Identity', formula: 'sin²θ + cos²θ = 1, 1 + tan²θ = sec²θ, 1 + cot²θ = cosec²θ' },
      { name: 'Area of Circle / Sector', formula: 'A = πr², Sector Area = (θ / 360°) × πr²' },
      { name: 'Volume of Sphere', formula: 'V = (4/3) πr³' },
    ],
  },
  {
    id: 'physics',
    subject: 'Physics (Class 10th)',
    grade: 'Class 10th',
    icon: '⚛️',
    description: 'Formula sheets and concepts',
    keyPoints: [
      'Refractive index n = c / v (speed of light in vacuum / medium).',
      'Ohm’s Law states V = I × R at constant temperature.',
      'In series: R_eq = R₁ + R₂ + ... + Rₙ. In parallel: 1/R_eq = 1/R₁ + 1/R₂ + ...',
      'Joule’s Heating effect: H = I²Rt = VIt = (V²/R)t.',
      'Right-Hand Thumb rule gives direction of magnetic field lines around straight current-carrying conductor.',
    ],
    formulas: [
      { name: 'Mirror Equation', formula: '1/f = 1/v + 1/u' },
      { name: 'Lens Equation', formula: '1/f = 1/v - 1/u' },
      { name: 'Magnification (Lens)', formula: 'm = v / u = h_image / h_object' },
      { name: 'Electric Power', formula: 'P = VI = I²R = V² / R' },
      { name: 'Electric Work / Energy', formula: 'E = P × t (1 kWh = 3.6 × 10⁶ J)' },
    ],
  },
  {
    id: 'chemistry',
    subject: 'Chemistry (Class 10th)',
    grade: 'Class 10th',
    icon: '🧪',
    description: 'Reactions and important topics',
    keyPoints: [
      'Oxidation is gain of oxygen or loss of electrons; Reduction is loss of oxygen or gain of electrons.',
      'pH < 7 indicates acidic solution; pH = 7 neutral; pH > 7 basic solution.',
      'Reaction of acid + metal carbonate -> Salt + CO₂ + H₂O.',
      'Plaster of Paris: CaSO₄ · ½H₂O prepared by heating Gypsum (CaSO₄ · 2H₂O) at 373 K.',
      'Homologous series: Same functional group, adjacent members differ by -CH₂- unit and 14 u mass.',
    ],
    formulas: [
      { name: 'Photosynthesis equation', formula: '6CO₂ + 6H₂O + Sunlight -> C₆H₁₂O₆ + 6O₂' },
      { name: 'Quicklime to Slaked Lime', formula: 'CaO(s) + H₂O(l) -> Ca(OH)₂(aq) + Heat' },
      { name: 'Bleaching Powder', formula: 'Ca(OH)₂ + Cl₂ -> CaOCl₂ + H₂O' },
      { name: 'Baking Soda Formation', formula: 'NaCl + H₂O + CO₂ + NH₃ -> NH₄Cl + NaHCO₃' },
      { name: 'Esterification Reaction', formula: 'CH₃COOH + C₂H₅OH (Acid) -> CH₃COOC₂H₅ + H₂O' },
    ],
  },
  {
    id: 'biology',
    subject: 'Biology (Class 10th)',
    grade: 'Class 10th',
    icon: '🧬',
    description: 'Diagrams and revision notes',
    keyPoints: [
      'Autotrophic nutrition involves chlorophyll capturing solar energy to split water into H₂ and O₂.',
      'Breakdown of glucose in cytoplasm yields pyruvate (3-carbon molecule) during glycolysis.',
      'Human heart has 4 chambers: Left atrium & ventricle pump oxygenated blood; Right pump deoxygenated blood.',
      'Functional unit of kidney is the Nephron, responsible for filtration, reabsorption, and urine formation.',
      'Mendel Law of Independent Assortment: Dihybrid cross phenotypic ratio is 9:3:3:1.',
    ],
    formulas: [
      { name: 'Glycolysis Site', formula: 'Glucose (6C) -> Cytoplasm -> 2 Pyruvate (3C) + 2 ATP' },
      { name: 'Aerobic Respiration', formula: 'Pyruvate + O₂ -> Mitochondria -> 6CO₂ + 6H₂O + 38 ATP' },
      { name: 'Anaerobic in Yeast', formula: 'Pyruvate -> Ethanol + CO₂ + 2 ATP' },
      { name: 'Monohybrid F2 Ratio', formula: 'Genotypic: 1:2:1 | Phenotypic: 3:1' },
      { name: 'Energy Transfer Rule', formula: 'Lindeman’s 10% Rule between trophic levels' },
    ],
  },
];

export const TESTS_DATA: TestItem[] = [
  // Class 12th Tests
  {
    id: 'class-12-physics-test',
    title: 'Class 12 Physics Test',
    subject: 'Physics',
    grade: 'Class 12th',
    badgeClass: 'blue',
    questionsCount: 20,
    durationMinutes: 30,
    questions: [
      {
        id: 1,
        question: 'Two point charges +q and +4q are placed at a distance L. Where should a third charge Q be placed on the line joining them so that the system is in equilibrium?',
        options: ['L/3 from +q', 'L/4 from +q', 'L/2 from +q', '2L/3 from +q'],
        correctIndex: 0,
        explanation: 'For equilibrium, forces from both charges must cancel. F₁ = kqQ/x² and F₂ = k(4q)Q/(L - x)². Equating gives x = L/3 from +q.',
      },
      {
        id: 2,
        question: 'What is the phase difference between current and voltage in a purely capacitive AC circuit?',
        options: ['Current lags voltage by π/2', 'Current leads voltage by π/2', 'In phase (zero)', 'Current leads voltage by π'],
        correctIndex: 1,
        explanation: 'In a purely capacitive circuit, charge and current lead the alternating EMF by a phase angle of π/2 radians (90°).',
      },
      {
        id: 3,
        question: 'A parallel plate capacitor with dielectric constant K has capacitance C. If the dielectric is removed, what is the new capacitance?',
        options: ['K × C', 'C / K', 'C - K', 'K² × C'],
        correctIndex: 1,
        explanation: 'Capacitance with dielectric is C = K · C₀, so without dielectric C₀ = C / K.',
      },
      {
        id: 4,
        question: 'In Young’s Double Slit Experiment (YDSE), if the distance between slits is halved and distance to screen is doubled, the fringe width becomes:',
        options: ['Unchanged', 'Doubled', '4 times', 'Halved'],
        correctIndex: 2,
        explanation: 'Fringe width β = λD/d. New β′ = λ(2D)/(d/2) = 4(λD/d) = 4β.',
      },
      {
        id: 5,
        question: 'The de Broglie wavelength of an electron accelerated through a potential difference of V volts is approximately:',
        options: ['12.27 / √V Å', '1.227 / √V Å', '122.7 / V Å', '0.1227 × √V Å'],
        correctIndex: 0,
        explanation: 'λ = h / √(2meV) = 1.227 / √V nm = 12.27 / √V Å.',
      },
    ],
  },
  {
    id: 'class-12-chemistry-test',
    title: 'Class 12 Chemistry Test',
    subject: 'Chemistry',
    grade: 'Class 12th',
    badgeClass: 'green',
    questionsCount: 20,
    durationMinutes: 30,
    questions: [
      {
        id: 1,
        question: 'The unit of rate constant for a first-order reaction is:',
        options: ['mol L⁻¹ s⁻¹', 'L mol⁻¹ s⁻¹', 's⁻¹', 'mol⁻² L² s⁻¹'],
        correctIndex: 2,
        explanation: 'For an n-th order reaction, unit is (mol L⁻¹)^(1-n) s⁻¹. For n = 1, it is s⁻¹.',
      },
      {
        id: 2,
        question: 'Which of the following compounds will undergo Cannizzaro reaction on treatment with 50% concentrated NaOH?',
        options: ['Acetaldehyde (CH₃CHO)', 'Benzaldehyde (C₆H₅CHO)', 'Acetone (CH₃COCH₃)', 'Propionaldehyde (CH₃CH₂CHO)'],
        correctIndex: 1,
        explanation: 'Aldehydes lacking α-hydrogen atoms (like Benzaldehyde and Formaldehyde) undergo Cannizzaro reaction.',
      },
      {
        id: 3,
        question: 'According to Crystal Field Theory, for a d⁴ octahedral complex in a strong ligand field (Δ₀ > P), the configuration is:',
        options: ['t₂g³ eg¹', 't₂g⁴ eg⁰', 't₂g² eg²', 't₂g¹ eg³'],
        correctIndex: 1,
        explanation: 'When Δ₀ > P (pairing energy), electrons pair up in the lower t₂g orbitals first, yielding t₂g⁴ eg⁰ (low spin).',
      },
      {
        id: 4,
        question: 'The van ’t Hoff factor (i) for complete dissociation of potassium ferricyanide K₃[Fe(CN)₆] is:',
        options: ['2', '3', '4', '5'],
        correctIndex: 2,
        explanation: 'K₃[Fe(CN)₆] dissociates into 3 K⁺ cations and 1 [Fe(CN)₆]³⁻ complex anion, giving 4 total ions (i = 4).',
      },
      {
        id: 5,
        question: 'Lanthanoid contraction is caused due to:',
        options: [
          'Poor shielding of 4f electrons by each other',
          'Imperfect shielding of 5d electrons',
          'Sharp decrease in nuclear charge',
          'High shielding power of f-orbitals',
        ],
        correctIndex: 0,
        explanation: 'The diffuse shape of 4f orbitals results in very poor shielding effect, allowing the increasing nuclear charge to draw outer electrons inward.',
      },
    ],
  },
  {
    id: 'class-12-maths-test',
    title: 'Class 12 Mathematics Test',
    subject: 'Mathematics',
    grade: 'Class 12th',
    badgeClass: 'purple',
    questionsCount: 20,
    durationMinutes: 30,
    questions: [
      {
        id: 1,
        question: 'If A is an invertible square matrix of order 3 and |A| = 5, then |adj(A)| is equal to:',
        options: ['5', '25', '125', '1/5'],
        correctIndex: 1,
        explanation: 'For an n×n matrix, |adj(A)| = |A|^(n-1). Here n = 3, so |adj(A)| = 5^(3-1) = 5² = 25.',
      },
      {
        id: 2,
        question: 'The integrating factor (I.F.) for the differential equation dy/dx + y·sec(x) = tan(x) is:',
        options: ['sec(x) + tan(x)', 'sec(x) · tan(x)', 'log|sec(x) + tan(x)|', 'tan(x)'],
        correctIndex: 0,
        explanation: 'I.F. = e^(∫ sec(x) dx) = e^(ln|sec(x) + tan(x)|) = sec(x) + tan(x).',
      },
      {
        id: 3,
        question: 'What is the value of ∫₀^(π/2) (sin³x / (sin³x + cos³x)) dx?',
        options: ['π', 'π/2', 'π/4', '0'],
        correctIndex: 2,
        explanation: 'Applying King’s Property ∫₀^a f(x)dx = ∫₀^a f(a-x)dx yields 2I = ∫₀^(π/2) 1 dx = π/2 => I = π/4.',
      },
      {
        id: 4,
        question: 'The direction cosines of a vector equally inclined to the three coordinate axes are:',
        options: ['(1, 1, 1)', '(1/√3, 1/√3, 1/√3)', '(1/3, 1/3, 1/3)', '(√3, √3, √3)'],
        correctIndex: 1,
        explanation: 'cos²α + cos²β + cos²γ = 1. Since α = β = γ, 3 cos²α = 1 => cos α = 1/√3. Hence (1/√3, 1/√3, 1/√3).',
      },
      {
        id: 5,
        question: 'If P(A) = 0.6, P(B) = 0.3 and P(A ∩ B) = 0.2, then what is P(A / not B)?',
        options: ['0.4', '0.57', '0.28', '0.67'],
        correctIndex: 1,
        explanation: 'P(A ∩ B\') = P(A) - P(A ∩ B) = 0.6 - 0.2 = 0.4. P(B\') = 1 - 0.3 = 0.7. P(A/B\') = 0.4 / 0.7 ≈ 0.57.',
      },
    ],
  },
  {
    id: 'weekly-13-12th',
    title: 'Weekly Test #13 (Class 12th PCM)',
    subject: 'Physics + Chemistry + Maths',
    grade: 'Class 12th',
    badgeClass: '',
    questionsCount: 30,
    durationMinutes: 45,
    questions: [
      {
        id: 1,
        question: 'In an LCR series AC circuit at resonance, the impedance Z of the circuit is:',
        options: ['Maximum and equal to R', 'Minimum and equal to R', 'Zero', 'Equal to ωL - 1/ωC'],
        correctIndex: 1,
        explanation: 'At resonance, inductive reactance equals capacitive reactance (X_L = X_C), making total impedance purely resistive and minimum: Z = R.',
      },
      {
        id: 2,
        question: 'Which of the following organic reagents converts an acid chloride (R-CO-Cl) into an aldehyde (R-CHO)?',
        options: ['LiAlH₄ in ether', 'H₂ / Pd-BaSO₄ (Rosenmund catalyst)', 'PCC in CH₂Cl₂', 'Zn-Hg / conc. HCl'],
        correctIndex: 1,
        explanation: 'Rosenmund reduction selectively reduces acid chlorides to aldehydes using poisoned Pd catalyst on BaSO₄.',
      },
      {
        id: 3,
        question: 'Find the projection of vector a = 2i + 3j + 2k on vector b = i + 2j + k:',
        options: ['5 / √6', '10 / √6', '8 / √6', '6 / √6'],
        correctIndex: 1,
        explanation: 'Projection = (a · b) / |b| = (2(1) + 3(2) + 2(1)) / √(1 + 4 + 1) = (2 + 6 + 2) / √6 = 10 / √6.',
      },
      {
        id: 4,
        question: 'What is the half-life of a first-order reaction with rate constant k = 2.31 × 10⁻³ s⁻¹?',
        options: ['100 s', '200 s', '300 s', '693 s'],
        correctIndex: 2,
        explanation: 't₁/₂ = 0.693 / k = 0.693 / (2.31 × 10⁻³) = 300 seconds.',
      },
      {
        id: 5,
        question: 'Electric flux through a Gaussian surface enclosing a dipole of charges +q and -q is:',
        options: ['q / ε₀', '2q / ε₀', 'Zero', 'q / 2ε₀'],
        correctIndex: 2,
        explanation: 'By Gauss’s law, Φ = Q_enclosed / ε₀. For an electric dipole, Q_enclosed = +q + (-q) = 0. Hence flux is zero.',
      },
    ],
  },

  // Class 10th Tests
  {
    id: 'algebra-test',
    title: 'Algebra Test',
    subject: 'Mathematics',
    grade: 'Class 10th',
    badgeClass: '',
    questionsCount: 20,
    durationMinutes: 30,
    questions: [
      {
        id: 1,
        question: 'If one zero of the quadratic polynomial x² + 3x + k is 2, then what is the value of k?',
        options: ['10', '-10', '-7', '-2'],
        correctIndex: 1,
        explanation: 'Substituting x = 2 into 2² + 3(2) + k = 0 gives 4 + 6 + k = 0 => k = -10.',
      },
      {
        id: 2,
        question: 'What is the nature of the roots of the quadratic equation 2x² - 4x + 3 = 0?',
        options: ['Real and equal', 'Real and distinct', 'No real roots', 'Rational and unequal'],
        correctIndex: 2,
        explanation: 'Discriminant D = b² - 4ac = (-4)² - 4(2)(3) = 16 - 24 = -8 < 0. Hence, no real roots.',
      },
      {
        id: 3,
        question: 'The 10th term of the arithmetic progression 2, 7, 12, ... is:',
        options: ['47', '52', '45', '50'],
        correctIndex: 0,
        explanation: 'Here a = 2, d = 5. a₁₀ = a + 9d = 2 + 9(5) = 2 + 45 = 47.',
      },
      {
        id: 4,
        question: 'If the pair of linear equations 2x + 3y = 7 and 4x + ky = 14 has infinitely many solutions, then k equals:',
        options: ['3', '6', '9', '12'],
        correctIndex: 1,
        explanation: 'For infinite solutions: a₁/a₂ = b₁/b₂ = c₁/c₂ => 2/4 = 3/k => 1/2 = 3/k => k = 6.',
      },
      {
        id: 5,
        question: 'What is the sum of first 20 natural numbers?',
        options: ['190', '200', '210', '220'],
        correctIndex: 2,
        explanation: 'Sum = n(n + 1)/2 = 20 × 21 / 2 = 210.',
      },
    ],
  },
  {
    id: 'physics-basics',
    title: 'Physics Basics',
    subject: 'Science',
    grade: 'Class 10th',
    badgeClass: 'green',
    questionsCount: 20,
    durationMinutes: 30,
    questions: [
      {
        id: 1,
        question: 'The unit of electric potential difference is:',
        options: ['Ampere', 'Volt', 'Ohm', 'Joule'],
        correctIndex: 1,
        explanation: 'Electric potential difference (V) is measured in Volts (V), named after Alessandro Volta.',
      },
      {
        id: 2,
        question: 'A convex mirror has a focal length of 20 cm. Its radius of curvature is:',
        options: ['10 cm', '20 cm', '40 cm', '30 cm'],
        correctIndex: 2,
        explanation: 'Radius of curvature R = 2f = 2 × 20 cm = 40 cm.',
      },
      {
        id: 3,
        question: 'Which law relates the electric current flowing through a conductor to the voltage across it?',
        options: ['Newton’s First Law', 'Ohm’s Law', 'Coulomb’s Law', 'Faraday’s Law'],
        correctIndex: 1,
        explanation: 'Ohm’s law states that V is directly proportional to I at constant physical conditions: V = IR.',
      },
      {
        id: 4,
        question: 'Power of a concave lens of focal length 2 metres is:',
        options: ['+0.5 D', '-0.5 D', '-2.0 D', '+2.0 D'],
        correctIndex: 1,
        explanation: 'P = 1/f. For concave lens, f = -2 m, so P = 1 / (-2) = -0.5 Dioptres.',
      },
      {
        id: 5,
        question: 'The commercial unit of electrical energy is kilowatt-hour (kWh). 1 kWh equals:',
        options: ['3.6 × 10⁵ J', '3.6 × 10⁶ J', '3.6 × 10⁷ J', '3.6 × 10⁴ J'],
        correctIndex: 1,
        explanation: '1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ Joules.',
      },
    ],
  },
  {
    id: 'grammar-test',
    title: 'Grammar Test',
    subject: 'English',
    grade: 'Class 10th',
    badgeClass: 'purple',
    questionsCount: 25,
    durationMinutes: 30,
    questions: [
      {
        id: 1,
        question: 'Choose the correct form: "Neither the teacher nor the students ______ present in class."',
        options: ['was', 'were', 'is', 'has been'],
        correctIndex: 1,
        explanation: 'When subjects are connected by neither/nor, the verb agrees with the closer subject ("students" is plural, so "were").',
      },
      {
        id: 2,
        question: 'Convert to passive voice: "She sang a melodious song."',
        options: [
          'A melodious song was sung by her.',
          'A melodious song is sung by her.',
          'A melodious song had been sung by her.',
          'A melodious song was being sung by her.',
        ],
        correctIndex: 0,
        explanation: 'Simple past "sang" changes to "was/were + past participle (sung)".',
      },
      {
        id: 3,
        question: 'Identify the sentence with correct punctuation and capitalisation:',
        options: [
          'He said "I will visit Paris tomorrow."',
          'He said, "I will visit Paris tomorrow."',
          'He said, "i will visit Paris tomorrow".',
          'He said "i will visit Paris tomorrow".',
        ],
        correctIndex: 1,
        explanation: 'Direct speech requires a comma before the quotation mark and capital letter inside.',
      },
      {
        id: 4,
        question: 'Choose the appropriate modal: "You ______ respect your elders and teachers."',
        options: ['might', 'ought to', 'would', 'may'],
        correctIndex: 1,
        explanation: '"Ought to" expresses moral obligation or duty.',
      },
      {
        id: 5,
        question: 'Identify the figure of speech: "The wind whispered through the dark forest."',
        options: ['Metaphor', 'Simile', 'Personification', 'Hyperbole'],
        correctIndex: 2,
        explanation: 'Giving human characteristics (whispering) to non-human elements (the wind) is Personification.',
      },
    ],
  },
  {
    id: 'weekly-13-10th',
    title: 'Weekly Test #13 (Class 10th)',
    subject: 'Mathematics + Science',
    grade: 'Class 10th',
    badgeClass: '',
    questionsCount: 30,
    durationMinutes: 45,
    questions: [
      {
        id: 1,
        question: 'If the zeroes of x² + px + q are double in value to the zeroes of 2x² - 5x - 3 = 0, find the value of q:',
        options: ['-6', '-12', '6', '12'],
        correctIndex: 0,
        explanation: 'Zeroes of 2x² - 5x - 3 are 3 and -1/2. Doubling gives 6 and -1. Product of new roots = 6 × (-1) = -6 = q.',
      },
      {
        id: 2,
        question: 'Which of the following processes is exothermic in nature?',
        options: ['Dissolution of ammonium chloride in water', 'Evaporation of water', 'Reaction of water with quick lime', 'Sublimation of camphor crystals'],
        correctIndex: 2,
        explanation: 'Reaction of quicklime (CaO) with water produces slaked lime along with a huge amount of heat (exothermic).',
      },
      {
        id: 3,
        question: 'The xylem in plants is responsible for:',
        options: ['Transport of water', 'Transport of food', 'Transport of amino acids', 'Transport of oxygen'],
        correctIndex: 0,
        explanation: 'Xylem conducts water and dissolved minerals from roots upwards to the aerial parts of the plant.',
      },
      {
        id: 4,
        question: 'A wire of resistance R is cut into five equal pieces. These pieces are connected in parallel. If the equivalent resistance of this combination is R′, then the ratio R/R′ is:',
        options: ['1/25', '1/5', '5', '25'],
        correctIndex: 3,
        explanation: 'Each piece has resistance R/5. In parallel: 1/R′ = 5 / (R/5) = 25/R => R/R′ = 25.',
      },
      {
        id: 5,
        question: 'What is the probability of getting a prime number when a fair die is rolled once?',
        options: ['1/6', '1/3', '1/2', '2/3'],
        correctIndex: 2,
        explanation: 'Prime numbers on a die are {2, 3, 5} (3 outcomes out of 6) => 3/6 = 1/2.',
      },
    ],
  },
];

export const INITIAL_RESULTS: TestResultRecord[] = [
  { id: 'wt-12', title: 'Weekly Test #12', score: 84, total: 100, date: '07 Sep 2026', subject: 'Math + Science' },
  { id: 'phy-01', title: 'Physics Basics', score: 78, total: 100, date: '02 Sep 2026', subject: 'Science' },
  { id: 'alg-01', title: 'Algebra Test', score: 91, total: 100, date: '28 Aug 2026', subject: 'Mathematics' },
];
